//! Injectable OAuth2 strategy functions.

pub mod sa_oauth2_create_access_token_value_function;
pub mod sa_oauth2_create_client_token_value_function;
pub mod sa_oauth2_create_code_value_function;
pub mod sa_oauth2_create_refresh_token_value_function;
pub mod sa_oauth2_grant_type_auth_function;
pub mod sa_oauth2_scope_work_access_token_function;
pub mod sa_oauth2_scope_work_client_token_function;

pub use sa_oauth2_create_access_token_value_function::SaOAuth2CreateAccessTokenValueFunction;
pub use sa_oauth2_create_client_token_value_function::SaOAuth2CreateClientTokenValueFunction;
pub use sa_oauth2_create_code_value_function::SaOAuth2CreateCodeValueFunction;
pub use sa_oauth2_create_refresh_token_value_function::SaOAuth2CreateRefreshTokenValueFunction;
pub use sa_oauth2_grant_type_auth_function::SaOAuth2GrantTypeAuthFunction;
pub use sa_oauth2_scope_work_access_token_function::SaOAuth2ScopeWorkAccessTokenFunction;
pub use sa_oauth2_scope_work_client_token_function::SaOAuth2ScopeWorkClientTokenFunction;
